### ISSUE TITLE
nvim 编辑文件提示错误

### ISSUE THREAD

**Issue by huangshengci** [Eatsolx/nvim-lua#1]
请问下问什么会提示这个错误呢? neovim 版本 v0.6.0
![image](https://user-images.githubusercontent.com/22500779/147222676-a1eff942-0d70-450f-858d-1d1c6e3c67db.png)

![image](https://user-images.githubusercontent.com/22500779/147222828-b8b2454b-52be-48bc-9911-168be7a71af1.png)

**Comment by sukai-cheng** [comment]
我也是，

**Comment by sukai-cheng** [comment]
up你在B站上做几期吧，好喜欢

**Comment by sukai-cheng** [comment]
![image](https://user-images.githubusercontent.com/35868545/147231466-d394d79f-1f73-4b57-97bc-acd5d63f8a37.png)

**Comment by sukai-cheng** [comment]
![image](https://user-images.githubusercontent.com/35868545/147231589-70d7feb3-f6c2-43c3-91e7-ff7acb62cdf6.png)

**Comment by Eatsolx** [comment]
请问0.5的有问题吗

**Comment by sukai-cheng** [comment]
我之前是0.4不行，然后现在是0.7的也不行

**Comment by Eatsolx** [comment]
此问题似乎出在nvchad。它那提了issue。https://github.com/NvChad/NvChad/issues/665 可以看一下

**Comment by Eatsolx** [comment]
使用leader uu更新一下，官方可能已经修复

**Comment by sukai-cheng** [comment]
up,嘿嘿😁，还有一个问题
![image](https://user-images.githubusercontent.com/35868545/147242718-1e7a5ec0-e3d4-4b64-8313-3e815f6fddc0.png)

**Comment by Eatsolx** [comment]
> 起来，嘿嘿😁，还有一个问题
> ![图片](https://user-images.githubusercontent.com/35868545/147242718-1e7a5ec0-e3d4-4b64-8313-3e815f6fddc0.png)你现在是什么版本？

**Comment by huangshengci** [comment]
> 

更新后可以了，感谢

**Comment by huangshengci** [comment]
> > 起来，嘿嘿😁，还有一个问题
> > ![图片](https://user-images.githubusercontent.com/35868545/147242718-1e7a5ec0-e3d4-4b64-8313-3e815f6fddc0.png)你现在是什么版本？

我用 V0.6.0 没有遇到这个问题
